### PR TITLE
Fix show button for filter columns

### LINKED ISSUE #328: Auto filter show button may not be honored
https://github.com/caxlsx/caxlsx/blob/f5931320eb700b059e145aeac41d18ee78e71a7d/lib/axlsx/workbook/worksheet/auto_filter/filter_column.rb#L45-L47

This does not allow to set `show_button` to false

### PR DESCRIPTION
**Pull request by kiskoza**
### Description

Closes #328 . Not just the reader was wrong, but the writer method too.

### Your checklist for this pull request

- [x] I have reviewed the [guidelines for contributing](../blob/master/CONTRIBUTING.md) to this repository.
- [x] I have added (or updated) appropriate tests if this PR fixes a bug or adds a feature.
- If this PR doesn't need tests (docs change), I added `[ci skip]` to the title of the PR.
- [x] If this closes any issues, I have added "Closes `#issue`" to the PR description or my commit messages.
- I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] I added an entry to the [changelog](../blob/master/CHANGELOG.md).

### CODE REVIEW

File: lib/axlsx/workbook/worksheet/auto_filter/filter_column.rb [hunk 1]
```diff
@@ -83,7 +85,7 @@ def hidden_button=(hidden)
     # @return [Boolean]
     def show_button=(show)
       Axlsx.validate_boolean show
-      @show_botton = show
```
Comment (tagliala) [inline lib/axlsx/workbook/worksheet/auto_filter/filter_column.rb:86]: I had to read this 3 times to actually find the error 😅
