### PR TITLE
Escape characters in charts

### LINKED ISSUE #37: Crashing chart caused by its title
I tried to create a chart with an `&` symbol in its name. When I opened it, it tried to recover the worksheet, said `Removed Part: /xl/drawings/drawing1.xml part.  (Drawing shape)` and got rid of the chart.

I know that xlsx is just a bunch of xml zipped into one file and `&` char has special meaning there. However, I haven't got an error for normal cells, https://github.com/randym/axlsx/issues/68 solved it already. Based on that ticket if I use the html escaped character (`&amp;`), it works fine.

My suggestion is to use the same string escape code for charts. 

Here is a sample code to reproduce the error with `v3.0.1`

```ruby
[
  { filename: 'sample', title: 'A and B' }, # Sample charrt, works fine
  { filename: 'failing', title: 'A & B' }, # Failing chart
  { filename: 'working', title: 'A &amp; B' }, # Working, but ugly solution
].each do |data|
  package = Axlsx::Package.new
  workbook = package.workbook
  sheet = workbook.add_worksheet(name: 'Chart Test')

  sheet.add_row ['&'] # Works with normal cells every time

  sheet.add_chart(Axlsx::BarChart, title: data[:title]) do |chart|
    chart.add_series data: [3, 7], labels: ['A', 'B'], title: data[:title]
  end

  package.serialize("#{data[:filename]}.xlsx")
end
```

As far as I know the required code is in [rich_text_run.rb](https://github.com/caxlsx/caxlsx/blob/master/lib/axlsx/workbook/worksheet/rich_text_run.rb#L207), we need to apply the same for charts.

### PR DESCRIPTION
**Pull request by kiskoza**
I'm making this PR to fix #37. 

There's an old test that required some changes: test/tc_axlsx.rb set the `Axlsx.trust_input` value to true which lead to ignore the CGI escapes.

All the other (new) tests are checking if the generated XMLs are valid or not with xml-specific special characters in the given title or cell.

### CODE REVIEW

File: test/drawing/tc_series_title.rb [hunk 1]
```diff
@@ -30,4 +30,25 @@ def test_cell
     assert(@title.text == "one")
   end
 
+  def test_to_xml_string_for_special_characters
+    @chart.add_series(title: @title, data: [3, 7], labels: ['A', 'B'])
+
+    @title.text = "&><'\""
+
+    doc = Nokogiri::XML(@chart.to_xml_string)
+    errors = doc.errors.map { |error| puts error.message; error }
```
Comment (noniq) [inline test/drawing/tc_series_title.rb]: Please remove the `puts` here (tests should not produce any output). To have these error messages available in case the test fails they could instead be appended to the message given as second argument to `assert`.

File: test/drawing/tc_series_title.rb [hunk 2]
```diff
@@ -30,4 +30,25 @@ def test_cell
...
+
+  def test_to_xml_string_for_special_characters_in_cell
+    @chart.add_series(title: @title, data: [3, 7], labels: ['A', 'B'])
+
+    cell = @row.cells.first
+    cell.value = "&><'\""
+    @title.cell = cell
+
+    doc = Nokogiri::XML(@chart.to_xml_string)
+    errors = doc.errors.map { |error| puts error.message; error }
```
Comment (noniq) [inline test/drawing/tc_series_title.rb]: Same as above.

File: test/tc_axlsx.rb [hunk 3]
```diff
@@ -24,8 +24,12 @@ def test_do_not_trust_input_by_default
 
 
   def test_trust_input_can_be_set_to_true
+    old = Axlsx.trust_input
```
Comment (noniq) [inline test/tc_axlsx.rb]:
```suggestion
    # Class variables like this are not reset between test runs, so we have
    # to save and restore the original value manually.
    old = Axlsx.trust_input
```

**Comment by kiskoza** [comment]
hi @noniq, thanks for the review, I resolved the issues

**Comment by noniq** [comment]
Merged. Thank you very much! 🎉
